services:

  caddy-webserver:
    image: caddy:2.7.5-alpine
    restart: always
    ports:
      - "8000:80"
      - "4443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    restart: always
